Repository OndrejHome/ansible.ha-cluster-pacemaker, pull requests merged in 2021-06, with the labels that each got.

#17 Manage resources, constraint, and properties
  README.md
  tasks/cluster_constraint_colocation.yml
  tasks/cluster_constraint_location.yml
  tasks/cluster_constraint_order.yml
  tasks/cluster_property.yml
  tasks/cluster_resource.yml
  tasks/cluster_resource_defaults.yml
  tasks/main.yml
Labels: enhancement, need_information

#18 Remove unsecure default password
  README.md
  tasks/main.yml
Labels: need_information

#19 Simplify vars loading
  redhat_repos.yml
  tasks/main.yml
  vars/redhat6.yml
  vars/redhat7.yml
  vars/redhat8.yml
Labels: enhancement

#20 Allow to disable PCSD GUI on Debian
  tasks/main.yml
  vars/debian10.yml
  vars/fedora31.yml
  vars/fedora32.yml
  vars/fedora33.yml
  vars/redhat6.yml
  vars/redhat7.yml
  vars/redhat8.yml
Labels: enhancement

#21 Fix issue on Centos 8.4 when enabling centos HA repository
  tasks/centos_repos.yml
Labels: enhancement
